### ISSUE TITLE
Pratica 1 checklist

### ISSUE THREAD

**Issue by vinny-vin** [vinny-vin/GCMS-Vinicius-Benicio.#2]
- [ ] Instalar Git localmente
- [ ] o Criar projeto local
- [ ] o Criar repositório local e realizar commits
- [ ] o Subir alterações para o repositório remoto
- [ ] o Fazer alterações no repositório da turma
@ramidedantas
